apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gkeCluster:
  cluster: prod
  location: us-central1
